### ISSUE TITLE
Controls Datei umbenennen

### ISSUE THREAD

**Issue by fhainz** [tobias-d-oe/fhem-uwz#1]
Hallo!

Ist es möglich die control-uwz.txt in controls_uwz.txt umzubenennen? Damit wäre es, mittels update add, möglich das Modul direkt in das FHEM-Update einfließen zu lassen. 
Derzeit quittiert FHEM mit dem Fehler: Usage: update add http://.../controls_.*.txt

Siehe http://fhem.de/commandref.html#update

Grüße

**Comment by tobias-d-oe** [comment]
erledigt

**Comment by fhainz** [comment]
danke funktioniert wunderbar!
